name: "Trigger: On Tag"

on:
  push:
    tags:
    - '*'
    - '**'

jobs:
  envs:
    runs-on: ubuntu-latest
    steps:
      - name: "print"
        run: |
          echo "--------------------- ENVS ---------------------"
          env
  maven_github_release:
    name: "maven"
    uses: YunaBraska/YunaBraska/.github/workflows/wc_maven_github_release.yml@main
    # has_pom                     ${{needs.maven_test.outputs.has_pom}}
    # changelog                   ${{needs.maven_test.outputs.changelog}}
    # java_version                ${{needs.maven_test.outputs.java_version}}
    # latest_tag                  ${{needs.maven_test.outputs.latest_tag}}
    # second_latest_tag           ${{needs.maven_test.outputs.second_latest_tag}}
    # semver_strategy             ${{needs.maven_test.outputs.semver_strategy}}
  maven_central_release:
    name: "maven"
    uses: YunaBraska/YunaBraska/.github/workflows/wc_maven_central_release.yml@main
    # has_pom                     ${{needs.maven_test.outputs.has_pom}}
    # java_version                ${{needs.maven_test.outputs.java_version}}
