name: "Tag: on Schedule"

on:
  workflow_dispatch:
    branches: [ main, master ]
  schedule:
    - cron: "0 5 * * *"

jobs:
  envs:
    runs-on: ubuntu-latest
    steps:
      - name: "print"
        run: |
          echo "--------------------- ENVS ---------------------"
          env
  maven_tag:
    name: "maven"
    uses: YunaBraska/YunaBraska/.github/workflows/wc_maven_tag.yml@main
    with:
      semver_strategy: rc
    # has_pom                     ${{needs.maven_test.outputs.has_pom}}
    # new_version                 ${{needs.maven_test.outputs.new_version}}
    # java_version                ${{needs.maven_test.outputs.java_version}}
    # project_version             ${{needs.maven_test.outputs.project_version}}
    # semver_strategy             ${{needs.maven_test.outputs.semver_strategy}}
    # has_publish_to_code_climate ${{needs.maven_test.outputs.has_publish_to_code_climate}}
