name: "Tag: on Schedule"

on:
  workflow_dispatch:
    branches: [ main, master ]
  schedule:
    - cron: "0 5 * * *"

jobs:
  envs:
    runs-on: ubuntu-latest
    steps:
      - name: "print"
        run: |
          echo "--------------------- ENVS ---------------------"
          env
  maven_tag:
    name: "maven"
    uses: YunaBraska/YunaBraska/.github/workflows/wc_maven_tag.yml@main
    with:
      semver_strategy: rc
    # has_pom                     ${{needs.maven_test.outputs.has_pom}}
    # new_version                 ${{needs.maven_test.outputs.new_version}}
    # java_version                ${{needs.maven_test.outputs.java_version}}
    # project_version             ${{needs.maven_test.outputs.project_version}}
    # semver_strategy             ${{needs.maven_test.outputs.semver_strategy}}
    # has_publish_to_code_climate ${{needs.maven_test.outputs.has_publish_to_code_climate}}
  maven_github_release:
    needs: maven_tag
    if: needs.tag.outputs.semver_strategy != ''
    name: "maven"
    uses: YunaBraska/YunaBraska/.github/workflows/wc_maven_github_release.yml@main
    # has_pom                     ${{needs.maven_test.outputs.has_pom}}
    # changelog                   ${{needs.maven_test.outputs.changelog}}
    # java_version                ${{needs.maven_test.outputs.java_version}}
    # latest_tag                  ${{needs.maven_test.outputs.latest_tag}}
    # second_latest_tag           ${{needs.maven_test.outputs.second_latest_tag}}
    # semver_strategy             ${{needs.maven_test.outputs.semver_strategy}}
  maven_central_release:
    needs: maven_tag
    if: needs.tag.outputs.semver_strategy != ''
    name: "maven"
    uses: YunaBraska/YunaBraska/.github/workflows/wc_maven_central_release.yml@main
    secrets:
      secrets: inherit
    # has_pom                     ${{needs.maven_test.outputs.has_pom}}
    # java_version                ${{needs.maven_test.outputs.java_version}}
